### ISSUE TITLE
Can't find PropertyChanging Attribute

### ISSUE THREAD

**Issue by sappho192** [kekyo/Epoxy#32]
Hello kekyo, I have a question about using `PropertyChanging` Attribute.

As the [Documentation](https://github.com/kekyo/Epoxy#viewmodel-injector-and-viewmodel-base-class), not only `PropertyChanged` but also `PropertyChanging` can be used.
But when I try to use it, VS can't find the symbol.

If I understood correctly, both following code can available, isn't it?

```C#
public WindowState MainWindowState { get; set; }
[PropertyChanging(nameof(MainWindowState))]
private ValueTask WindowStateChanged(WindowState state)
{
	MainShowInTaskbar = true;
	return default;
}
```

```C#
public WindowState MainWindowState { get; set; }
[PropertyChanged(nameof(MainWindowState))]
private ValueTask WindowStateChanged(WindowState state)
{
	if (state == WindowState.Minimized)
	{
		MainShowInTaskbar = false;
	}
	return default;
}
```

Is `PropertyChanging` Attribute not been implemented yet?

**Comment by kekyo** [comment]
Ah, you found the week point 😄 

Currently this is a limitation of Epoxy and there is no way to hook PropertyChanging. However, I am open to implementing it.

When I initially thought about how to hook PropertyChanging and PropertyChanged, I assumed that PropertyChanging's reason for existence was to get the value before the change:

```csharp
[PropertyChanged(nameof(MainWindowState))]
private ValueTask WindowStateChanged(WindowState oldState, WindowState newState)
{
    // ...
}
```

This method is internally close to the one employed by Avalonia, and we thought it was reasonable. However, there is a tradeoff:

* It is difficult to know whether old or new value should be placed at the beginning of the argument.
  * Since the PropertyChanged handler is already duck typing, this makes it easier to lead to the wrong implementation.
* This is not applicable when you want to take action before the value is changed (in this case).

On the other hand, if you clearly separate it from PropertyChanging as you have presented it:

* Internal implementation of Epoxy is not so difficult.
* If we want to monitor old values with PropertyChanged, we have to go to the trouble of keeping those values somewhere, which puts the implementer under the stress of state management.

I thought that the best way to integrate the two would be to use PropertyChanging, but since there was no need for PropertyChanging at the time, it has been neglected to this day.

Do you have any input on this? I would like to take a look at the implementation.

**Comment by sappho192** [comment]
なるほどですね！ I see 😄 
Thank you for the detailed explanation.

In fact, I had a funny situation that it **seemed** to implement some code before the `PropertyChanged` fires (because the feature I wanted to implement didn't work at that time), but it worked implementing them within `PropertyChanged` (!?).
So actually I don't need `PropertyChanging` Attribute for now, but the red lines below the `PropertyChanging` in VS (which means can't find the implementation or symbol) kept making me feel ask a question about this.

My original goal was to implement `Minimize into Windows tray` in WPF with MVVM way.
Then I found a [[Blog post](https://roundwide.com/implementing-system-tray-app-with-wpf-and-mvvm)] with an example [[Github code](https://github.com/fujieda/SystemTrayApp.WPF)] so I tried to implement the feature based on this example code.

Following code is a part of example Github code that hides the Window after minimized:
```C#
private bool _showInTaskbar;
public bool ShowInTaskbar
{
    get => _showInTaskbar;
    set { SetProperty(ref _showInTaskbar, value);
}      

private Windowstate _windowState;
public WindowState WindowState
{
    get => _windowState;
    set
    {
        ShowInTaskbar = true;
        SetProperty(ref _windowState, value);
        ShowInTaskbar = value != WindowState.Minimized;
    }
}
```

and below is my implementation:
```C#
public bool MainShowInTaskbar { get;set; }
[PropertyChanged(nameof(MainShowInTaskbar))]
private ValueTask ShowInTaskbarChanged(bool showInTaskbar)
{
	if (showInTaskbar)
	{
		MainWindowState = WindowState.Normal;
	}
	return default;
}

public WindowState MainWindowState { get; set; }
[PropertyChanged(nameof(MainWindowState))]
private ValueTask WindowStateChanged(WindowState state)
{
	MainShowInTaskbar = true;
	if (state == WindowState.Minimized)
	{
		MainShowInTaskbar = false;
	}
	return default;
}
```
```XAML
<Window x:Class="Something.MainWindow"
        ...
        ShowInTaskbar="{Binding MainShowInTaskbar}"
        WindowState="{Binding MainWindowState}">
```


At first, the Window didn't properly minimized with remaining Window like this:  
![image](https://user-images.githubusercontent.com/7788738/221390993-56ca7745-f7cb-4140-beab-ad2c79810d9f.png)

I thought `MainShowInTaskbar = true;` in `WindowStateChanged()` should be called right before `WindowStateChange()`.
But I simply solved this problem with adding same code in the constructor:
```C#
public MainWindowViewModel()
{
	MainShowInTaskbar = true;
```
Maybe the problem was not setting initial value manually made this bool to be begin as `false` 😂 

> On the other hand, if you clearly separate it from PropertyChanging as you have presented it:
> - Internal implementation of Epoxy is not so difficult.
> - If we want to monitor old values with PropertyChanged, we have to go to the trouble of keeping those values somewhere, which puts the implementer under the stress of state management.

Then maybe I can try contributing Epoxy with implementing `PropertyChanging`! 
It may be a good oppertunity since I still have no self-confidence in understanding on MVVM. 

Thank you 😀

**Comment by kekyo** [comment]
Oh, this is hard for me to understand 😄

In this story, I'm getting around this by setting the initial state (to an expected value) in the constructor, but I think it's not a problem 👍

> Then maybe I can try contributing Epoxy with implementing PropertyChanging!
> It may be a good oppertunity since I still have no self-confidence in understanding on MVVM.

PRs are welcome, but maybe it's difficult... When if you try to it, snapping points are:

* The basic structure is `PropertyChanging` compliant so that `PropertyChanging` can be handled when using `ViewModelBase`. However, the problem is that Epoxy.Build does not hook `PropertyChanging`.
* There is a place in Epoxy.Build that generates embedded code for `PropertyChanged`. So add code to have it generate the embed code for `PropertyChanging` as a similar code.
* You probably need to declare a delegate type for `PropertyChanging`. For `PropertyChanged` it is defined as `PropertyChangedAsyncDelegate<T>`. Since this will be the delegate type for calling the method to which the attribute is applied, we will have a delegate type for `PropertyChanging` as well, and use this type on the Epoxy.Build side.

### As a side note

One of the problems with MVVM is that it reflects the initial state of the property binding system. Should the initial values be supplied as defined by the control's properties or by the view model? This is the question.

I guess this depends on the binding engine implementation, but in this case it is because `Window.ShowInTaskbar` did not transfer the initial values to the view model side at binding time.

Binding engines such as WPF is wanted the property values to be transferred to the view model when the binding is established. However, if we let this behavior happen, the cost of the binding is increased and it becomes impossible if we want to transfer the initial values from the view model.

The binding system is a better structure, but it is not perfect, and I personally think it is better not to go too deep into it, because there are some problems such as the lack of clear subject-object relationship and the difficulty in dealing with triggers of events.

**Comment by kekyo** [comment]
As I was writing the above reply, a little question arose in the code, so I will look into it again before continuing ;)

**Comment by kekyo** [comment]
[Around this of Epoxy.Build](https://github.com/kekyo/Epoxy/blob/main/src/Epoxy.Build/ViewModelInjector.cs#LL398C27-L398C27) is where the ` PropertyChangedAttribute` and generate code for it. I think that similar code could be inserted here to support `PropertyChangingAttribute`.

It is okay if it is too difficult to implement. Even if you give up, I maybe implement it in later :)

**Comment by sappho192** [comment]
Thank you for such a detailed explanation and tips. 

> The binding system is a better structure, but it is not perfect, and I personally think it is better not to go too deep into it, because there are some problems such as the lack of clear subject-object relationship and the difficulty in dealing with triggers of events.

Yes, recently I started to realizing this at some point. It is very paradoxical that the more I get to know, the more I don't know. 😂

> It is okay if it is too difficult to implement. Even if you give up, I maybe implement it in later :)

Actually I'm little intimidated of decompiler and source generater codes in Epoxy.Build, but I still want to give it a try! Thank you :)
