### ISSUE TITLE
Avalonia11 PublishAot Events Binding invalid

### ISSUE THREAD

**Issue by cbuduknui** [kekyo/Epoxy#44]
Avalonia version : 11.0.10
Epoxy.Avalonia11 : 1.14.0
.net version：8.0

Pusblish Application apply below settings,events Binding invalid.
<PublishAot>true</PublishAot>

I try add rd.xml，test ok. I was wondering if I could get out of this procedure
	<ItemGroup>
		<RdXmlFile Include="rd.xml" />
	</ItemGroup>

rd.xml content:
<?xml version="1.0" encoding="utf-8"?>
<Directives>
    <Application>
		<Assembly Name="AvaloniaA1" Dynamic="Required All"/>
        <Assembly Name="Epoxy.Core" Dynamic="Required All"/>
		<Assembly Name="Epoxy" Dynamic="Required All"/>
    </Application>
</Directives>

ep:EventBinder.Events
<ep:Event Command="{Binding ViewLoaded}" EventName="Loaded" />
</ep:EventBinder.Events>

public string Greeting { get; set; } = "Welcome to Avalonia!";
public Command ViewLoaded { get; }

public MainViewModel()
{
this.ViewLoaded = Command.Factory.Create(() =>
{
Greeting = "Hello!";
return default;
});
}

ViewLoaded command not invoke.

**Comment by kekyo** [comment]
In conclusion, for `EventBinder` and `GlobalService`, I don't think they can be used in NativeAOT at present.

* `EventBinder` hooks .NET events using reflection internally.
  This is because it identifies the event to be hooked from the event name string, this part is considered problematic for NativeAOT.
* `GlobalService` because it uses reflection to compose the type corresponding to the interface type it manages, event as well as NativeAOT is not supported.

In both cases, there are ideas for solutions that would improve Epoxy's implementation:

* EventBinder` could be written in Epoxy.Build to do static parsing and generation at build time, which would be a complete change from the way it is written current syntax.
* GlobalService` can be processed in the same way in Epoxy.Build.

However, the implementation difficulty of both is quite high, so it is difficult to support them right now.
(We are open to considering EventBinder.)
